baseURL = "https://your-site-name.netlify.app/"
languageCode = "en-us"
title = "Office Tech Flow"
theme = "ananke"

[params]
  ananke_socials = [
    { name = "github", url = "https://github.com/your-username/your-repo" },
  ]
