baseURL = "https://office-tech-flow.netlify.app/"
languageCode = "en-us"
title = "Office Tech Flow"
theme = "ananke"

[params]
  ananke_socials = [
    { name = "github", url = "https://github.com/gabec05/revenue-engine-zerocost" },
  ]
