name: Automated Publishing

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 PM UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run content generation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: "Keywords"
        run: python scripts/generate_and_publish.py
        
      - name: Build Hugo site
        run: hugo

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/
          git add public/
          git commit -m "Automated content update" || echo "No new content to commit"
          git push
